import Head from "next/head";
import Navbar from "./components/Navbar";
import AlcoholItem from "./components/AlcoholItem";
import Footer from "./components/Footer";



export default function Home() {
  return (
    <>
    <Head>
        <title>William MacMiron</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
    <Navbar/>
    <AlcoholItem/>
    <Footer/>
  </>
  );
}
